title: POO
description: Apuntes, ejercicios, material de apoyo y reportes técnicos para el módulo [ICC490-1] de POO.
remote_theme: just-the-docs/just-the-docs
baseurl: "/ICC490-1-POO"
lang: es
search_enabled: true
plugins:
  - jekyll-remote-theme
color_scheme: rosepine
defaults:
  - scope:
      path: "3.Clases"
      type: "pages"
    values:
      nav_exclude: true
      search_exclude: true
exclude:
  - 3.Clases/
